### ISSUE TITLE
How can I call restricted get_channel_entry?

### ISSUE THREAD

**Issue by samaphp** [putyourlightson/open-api#29]
Hi their, Thanks for this awesome API it's amazing.
But I'm trying to call this method get_channel_entry() while I mark it as a (restricted), I'm trying to pass session_id but still I'm getting (You are not permitted to perform this action).

I mean how can I request this URL by authenticated user? because this method is not public!
http://private-anon-6696b2834-eeopenapi.apiary-mock.com/get_channel_entry?entry_id=1

Many Thanks,
Saud

**Comment by davorpeic** [comment]
Hey @samaphp did you found a solution for you? trying to gain access from mobile angular and not using cookies, but it seems that it will not work :(

thanks

**Comment by davorpeic** [comment]
I switched to universal api at this moment

**Comment by helmi-pts** [comment]
@davorpeic can you clarify what is universal api? is it for EE? Thanks.

**Comment by davorpeic** [comment]
@helmi-pts My bad, I was referring to universal api key to access all restricted endpoints
![universal_api_key](https://cloud.githubusercontent.com/assets/694091/10135076/f52b99cc-65b8-11e5-9c3f-631647d6fa36.jpg)
