### ISSUE TITLE
New Entry with categories

### ISSUE THREAD

**Issue by mario-arenas** [putyourlightson/open-api#30]
Hi Ben,

This is awesome work and thank you for releasing it to the community.
Also, I was wondering if the create_channel_entry operation supports categories. In short, I'd like to add a new entry with categories.

Please let me know when you have a chance.

Thanks,
Mario

**Comment by putyourlightson** [comment]
hi mario, this should work by passing in the categories as an array as follows:

    'category' => array(1, 3, 5)

**Comment by mario-arenas** [comment]
Thank you for the response. Will give it a shot.

Mario
