### ISSUE TITLE
Api key available in authorize endpoint

### ISSUE THREAD

**Issue by davorpeic** [putyourlightson/open-api#31]
Hi @putyourlightson,

I'm building mobile app, and I found very hard to send cookies and deal with sessions and CORS at the same time. So I modified authorize_email() to return universal api key once user gets authenticated. Later, that key can be used to obtain access to the api, and if I need to reset the api_key, I can do it easily from the Admin, and mobile user will need to login again to obtain new api_key.

I saw other people were asking for similar features, so my question to you is do you think this is something worth PR and having this feature built in?

Thanks
Davor

**Comment by putyourlightson** [comment]
hi davor and thanks for the suggestion. my concern with doing this though is that you might inadvertently give a user read access to a channel that their member group should not have access to. perhaps this is being slightly pedantic but my preference is for predictability and consistency in an api. not sure if I can help with the CORS issue you are having but I've seen mobile apps interact with the api so I know it's possible.

**Comment by davorpeic** [comment]
Hm, well I'm using angular and I spent too much of my time trying to work with cookie sessions, so based on my actual knowledge this was the shortcut, and I really appreciate the insights, I'm aware that this solution is not the best, but for this small project it works fine, if I find better solution will post it or do a PR.

thanks

**Comment by putyourlightson** [comment]
sounds good and best of luck on your project!!
