### ISSUE TITLE
Some URIs are missing in Apiary documentation

### ISSUE THREAD

**Issue by DanielHarold** [putyourlightson/open-api#32]
In the Reference documentation on Apiary (http://docs.eeopenapi.apiary.io/#reference), several API calls' URIs are not showing up in the documentation.

For example, under [Channel Entries](http://docs.eeopenapi.apiary.io/#reference/channel-entries), the URI `/get_channel_entry?entry_id=1` appears, but the URI for `/get_channel_entries` does not show up:

![get_channel_entry](https://user-images.githubusercontent.com/10429715/27970469-fd8b4b86-631c-11e7-8e07-bd57e19a7600.png)

This makes it look like the URI `/get_channel_entry` can be used either to get a single entry or to get a list of entries, depending on the parameters given.

**Comment by putyourlightson** [comment]
Apiary recently changed their API syntax so I believe a lot of methods are now not appearing as they should. The most reliable way to see what is available is still in the code itself here:
[https://github.com/putyourlightson/open-api/blob/master/open-api/system/expressionengine/third_party/open_api/libraries/Open_api_lib.php](https://github.com/putyourlightson/open-api/blob/master/open-api/system/expressionengine/third_party/open_api/libraries/Open_api_lib.php)
